### ISSUE TITLE
Support upper case file extensions

### ISSUE THREAD

**Issue by reinvantveer** [Geodan/point-cloud-colorize#4]
process_files only accepts lowercase file extensions.
see https://github.com/Geodan/point-cloud-colorize/blob/master/point_cloud_colorize/las_colorize.py#L128, 
but PDOK serves uppercase file extensions, such as https://geodata.nationaalgeoregister.nl/ahn3/extract/ahn3_laz/C_10AZ2.LAZ

**Comment by chrislcs** [comment]
Should be fixed with 2bf6be4
